name: CI

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 6am UTC
    - cron: '0 6 * * 1'
  push:
    branches:
      - master
      - stable
      - '*.x'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      # Any env name which does not start with `pyXY` will use this Python version.
      default_python: '3.9'
      envs: |
        - linux: py310
        - linux: coverage
        - linux: py38
        - macos: py39
        - linux: compatibility
        - linux: codestyle
        - linux: docbuild
          libraries:
            apt:
              - graphviz
        - linux: twine
        - linux: py39-astropydev
        - linux: py39-asdfastropydev
        - linux: py39-gwcsdev
        - linux: py39-numpydev
        - linux: py39-asdfstandarddev
        - linux: py39-asdftransformschemasdev
        - linux: py39-asdfwcsschemasdev
        - linux: py39-asdfcoordinatesschemasdev
        - linux: prerelease
        - linux: packaged
        - linux: warnings
        - windows: py39

  asdf-standard:
    name: Run asdf-standard tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout asdf
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: asdf
      - name: Checkout asdf-standard
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: asdf-format/asdf-standard
          ref: master
          path: asdf-standard
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install asdf
        run: cd asdf && pip install .
      - name: Install asdf-standard
        run: cd asdf-standard && pip install -e .[test]
      - name: Pip Freeze
        run: pip freeze
      - name: Run asdf-standard tests
        run: cd asdf-standard && pytest
