---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: backport-2.15.x,development
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  changelog:
    name: Confirm changelog entry
    runs-on: ubuntu-latest
    needs: [check_labels]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Grep for PR number in CHANGES.rst
        run: grep -P '\[[^\]]*#${{github.event.number}}[,\]]' CHANGES.rst
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-entry-needed') }}
